# Generated by Django 4.0.4 on 2022-05-20 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0003_receita_pessoa_alter_receita_date_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='date_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 20, 13, 58, 55, 902253)),
        ),
    ]
